#!/usr/bin/env bash
# config script
apt-get -y update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8

apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "
frontend http
    bind *:80
    mode http
    default_backend web-backend
backend web-backend
        balance roundrobin
        server 859-web-01 35.243.178.52 check
        server 859-web-02 34.74.213.65 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
