#!/usr/bin/env bash
# config script
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6

sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

echo
"backend web-backend
balance roundrobin
server 859-web-01 35.243.178.52 check
server 859-web-02 34.74.213.65 check

frontend http
bind *:80
mode http
default_backend web-backend" >> /etc/haproxy/haproxy.cfg

service haproxy restart