#!/usr/bin/env bash
#echos Holberton School * 10
a=0
while [ $a -lt 10 ];
do
      if [ $a -eq 3 ]
      then
	  echo "bad luck"
      elif [ $a -eq 7 ]
      then
	  echo "good luck"
      else
	  echo "Holberton School"
      fi
          ((a++))
done
