#!/usr/bin/env bash
#echos Holberton School * 10
a=1
while [ $a -lt 21 ]
do
    echo $a
    case $a in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    (( a++ ))
done
